/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DAYUHANHOTEL;

import screen.SplashScreen;

public class App {

    public static void main(String[] args) {
        new SplashScreen().setVisible(true);

    }
}
